# Generated by Django 2.1.7 on 2019-04-04 19:34

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields
import mainapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='aaa', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q', models.TextField(max_length=10000)),
                ('q_id', models.CharField(max_length=10)),
                ('text_id', models.CharField(blank=True, max_length=30, null=True)),
                ('chosen_ans', models.CharField(blank=True, max_length=10, null=True)),
                ('a', models.CharField(max_length=1000)),
                ('b', models.CharField(max_length=1000)),
                ('c', models.CharField(max_length=1000)),
                ('d', models.CharField(max_length=1000)),
                ('e', models.CharField(max_length=1000)),
                ('topic_id', models.CharField(max_length=30)),
                ('topic_name', models.CharField(max_length=200)),
                ('topic_video_link', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=10)),
                ('weight', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Question2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q', models.TextField(max_length=10000)),
                ('q_id', models.CharField(max_length=10)),
                ('chosen_ans', models.CharField(blank=True, max_length=10, null=True)),
                ('right_ans_nums', models.CharField(max_length=10)),
                ('a', models.CharField(max_length=1000)),
                ('b', models.CharField(max_length=1000)),
                ('c', models.CharField(max_length=1000)),
                ('d', models.CharField(max_length=1000)),
                ('e', models.CharField(max_length=1000)),
                ('f', models.CharField(max_length=1000)),
                ('g', models.CharField(max_length=1000)),
                ('h', models.CharField(max_length=1000)),
                ('topic_id', models.CharField(max_length=30)),
                ('topic_name', models.CharField(max_length=200)),
                ('topic_video_link', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=10)),
                ('weight', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
                ('questions', djongo.models.fields.ArrayModelField(model_container=mainapp.models.Question)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectWithEightAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=200)),
                ('questions1_20', djongo.models.fields.ArrayModelField(model_container=mainapp.models.Question)),
                ('questions21_30', djongo.models.fields.ArrayModelField(model_container=mainapp.models.Question2)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectWithTexts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
                ('texts', djongo.models.fields.ArrayModelField(model_container=mainapp.models.Text)),
                ('questions', djongo.models.fields.ArrayModelField(model_container=mainapp.models.Question)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='SOME STRING', max_length=50, verbose_name='Название')),
                ('variant', models.IntegerField(default=1, verbose_name='Вариант')),
                ('price', models.IntegerField(default=1, verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=10000)),
                ('text_id', models.CharField(max_length=10)),
                ('question_number', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='testt',
            name='id',
        ),
        migrations.AddField(
            model_name='testt',
            name='_id',
            field=djongo.models.fields.ObjectIdField(auto_created=True, default='5c4827ae923dac16a72a9d61', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='testt',
            name='cost',
            field=models.IntegerField(default=200),
        ),
        migrations.AddField(
            model_name='testt',
            name='lang_id',
            field=models.IntegerField(default='1'),
        ),
        migrations.AddField(
            model_name='testt',
            name='lang_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='testt',
            name='subject_1',
            field=djongo.models.fields.EmbeddedModelField(model_container=mainapp.models.Subject, null=True),
        ),
        migrations.AddField(
            model_name='testt',
            name='subject_12',
            field=djongo.models.fields.EmbeddedModelField(model_container=mainapp.models.SubjectWithEightAnswer, null=True),
        ),
        migrations.AddField(
            model_name='testt',
            name='subject_13',
            field=djongo.models.fields.EmbeddedModelField(model_container=mainapp.models.SubjectWithEightAnswer, null=True),
        ),
        migrations.AddField(
            model_name='testt',
            name='subject_2',
            field=djongo.models.fields.EmbeddedModelField(model_container=mainapp.models.SubjectWithTexts, null=True),
        ),
        migrations.AddField(
            model_name='testt',
            name='subject_3',
            field=djongo.models.fields.EmbeddedModelField(model_container=mainapp.models.Subject, null=True),
        ),
        migrations.AddField(
            model_name='forcheck',
            name='que',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Question'),
        ),
    ]
